# Generated by Django 3.2 on 2022-12-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('comment_date',), 'verbose_name': 'Comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='body_ar',
            field=models.TextField(help_text='Your comment', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_en',
            field=models.TextField(help_text='Your comment', null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_ar',
            field=models.CharField(help_text='Your name', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_en',
            field=models.CharField(help_text='Your name', max_length=50, null=True, verbose_name='name'),
        ),
    ]
