# Generated by Django 3.2 on 2022-12-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=32, null=True, verbose_name='name'),
        ),
    ]
